remote_theme: pages-themes/minimal@v0.2.0
title: Material de Curso
description: Taller de introducción a las redes neuronales con TensorFlow
author: Julio Waissman
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
